//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TId { get; set; }
        public string TName { get; set; }
        public string TEmail { get; set; }
        public string TSlogan { get; set; }
    }
}
